### ISSUE TITLE
CCTileMap: Elegantly handle drawing of tile map with vertices > 65535

### ISSUE THREAD

**Issue by rtabbara** [mono/CocosSharp#148]
Driven by #147

Drawing tile maps as indexed primitives requires an index buffer whose values are stored as unsigned shorts. But this means that the max number of vertices we can have is limited to 2^16 - 1 = 65535. Each tile consists of 4 verts, so alternatively we're restricted to a total number of  65535/ 4 = 16384 tiles *per draw call*

To handle this, we should allow for multiple vertex/index buffers that would each have their own draw call.

**Comment by charliekilian** [comment]
Is there a timeline for when this will be worked on? If there are no immediate plans to fix it (and hey, I understand -- I get that there are tons of pressing issues and tasks), I would like to take a crack at it. If that sounds okay to you, do you have any advice on how to proceed? Right now I'm planning on creating a class that is private to CCTileMapLayer that contains both the vertex and index buffer classes. Then it'll create as many of those as it needs to render all the tiles, with each containing up to 16384 tiles.

Does this sound like the correct approach, or did you have something else in mind?

**Comment by rtabbara** [comment]
By all means, please. What you've suggested sounds like a good approach. Just please keep in mind within your design to accommodate for the upcoming enhancement to only draw tiles that are visible on the screen. In particular, this means that your internal classes that contain the vertex/index buffers will need to keep track of the vertex/index ranges that should be drawn.

**Comment by kjpou1** [comment]
Should we be thinking of a more generic approach here?  It seems to me that a more generic solution that will benefit all classes and not just tilemaps would be to change the DrawBuffer method in CCDrawManager itself https://github.com/mono/CocosSharp/blob/master/src/platform/CCDrawManager.cs#L732 

The limit of 16384 could also be determined by platform as well.  Maybe this would be good for some mobile platforms but Windows and Mac desktop definitely handle larger buffers than a mobile device so we have limited those to more draw calls.

**Comment by charliekilian** [comment]
Since I was basically done with the work besides some cleanup before @kjpou1's comment came in, I went ahead and pushed it to a branch in case anyone wants to see what I did. This follows the implementation strategy that I discussed with @rtabbara. 

Regardless of how it gets solved, I'm going to have to create a test for this issue. I won't get around to that until this weekend at the earliest. 

I am not fully understanding Kenneth's suggestion, but I suspect once I review the CCDrawManager class in some more depth I'll understand better. From the sounds of it, it would still be necessary to do the work of managing multiple draw calls for some mobile devices, right? If that is the case, then perhaps the work I did tonight will still be useful.

If anyone has the time and inclination to review the work I've done so far and give me feedback, I'd love to hear your thoughts.

**Comment by kjpou1** [comment]
@charliekilian 

I wee what you mean now with the 16384.  It is the index buffer not vertices and makes sense now.  Sorry for the confusion.

**Comment by rtabbara** [comment]
@charliekilian I've taken a look at your local branch and it looks really good. Would you be able to please raise a PR so that we can merge?

**Comment by charliekilian** [comment]
I've created the pull request.

**Comment by rtabbara** [comment]
@charliekilian Thanks! We'll look to merge this asap.

**Comment by kjpou1** [comment]
This is closed by https://github.com/mono/CocosSharp/pull/159
