### ISSUE TITLE
CCFadeOutBLTiles leaks memory

### ISSUE THREAD

**Issue by Krumelur** [mono/CocosSharp#168]
See demo at: https://dl.dropboxusercontent.com/u/111612273/CCFadeOutBLTiles_Issue.zip

* Deploy to an iOS device (not in the Simulator!)
* Start the app with Instruments, using the "Allocations" tool.
* Mark the heap to set a start value.
* Tap the screen to show a `CCSprite` which will immediately be destroyed after running `CCFadeOutBLTiles`
* Repeat this a couple of times
* Mark the heap in Instruments again

Memory will quickly grow to more than 1MB and never be released again. 

![bildschirmfoto 2015-04-07 um 00 35 44](https://cloud.githubusercontent.com/assets/574373/7013941/76ba611e-dcbe-11e4-8b26-3af44ef23314.png)

**Comment by kjpou1** [comment]
Rene

A couple of things in the sample.  

1) After running the effect you will need to set the Grid being used to -> null  <-.  If not then the grid still hangs around and during the visit there are still render targets being allocated and still being rendered too and swapped out.


		await this.RunActionAsync(new CCFadeOutBLTiles(1f, new CCGridSize(10, 10)));

                // Make sure we unset our grid that was attached.
                this.Grid = null;

Now even after setting the Grid to null, just to be even surer what I did in the commit https://github.com/mono/CocosSharp/commit/6755b64e678a4a1140af7febd32cd85aa772dfb8 was specifically call Dispose() on the Grid, when you set it to null or any other value for that matter, so that the backing Texture that the effect uses is definitely marked as being Disposed of.  That way we are sure it gets disposed.

2) There is a message being logged that is 

2015-04-07 09:05:22.894 CocosTest[33271:28932743] Obsolete -- Grid Actions should only target CCNodeGrids.
Obsolete -- Grid Actions should only target CCNodeGrids.

The Grid attached to a CCNode is now obsolete.

The new code can read as:

		async void OnTouchesEnded (List<CCTouch> touches, CCEvent touchEvent)
		{
			if (touches.Count > 0)
			{
                var targetNode = new CCNodeGrid();
                AddChild(targetNode);

                //lbl = new CCSprite("images/bat2.png");
				lbl = CreateLabel (string.Format("Score: {0:n0} - Level: {1}", 123456, count), 30, CCColor3B.Yellow, CCColor3B.Blue);
				lbl.Position = this.ContentSize.Center;
                targetNode.AddChild(lbl);
				count++;

				await targetNode.RunActionAsync(new CCFadeOutBLTiles(1f, new CCGridSize(10, 10)));

                // Make sure we unset our grid that was attached.
                targetNode.Grid = null;

				lbl.RemoveFromParent();
				lbl = null;	

                targetNode.RemoveFromParent();

				GC.Collect ();
				GC.WaitForPendingFinalizers ();
				GC.Collect ();
			}
		}

Please verify if this helps with the memory leak.  You can test the before and after of the commit references but you will still need to set the Grid to null.

**Comment by Krumelur** [comment]
Thanks for the update and info. It's hard to understand from a user perspective that one has to create a CCNodeGrid first and must clean up the Grid property manually. Could be lack of documentation but why can't the grid be nulled out and disposed automatically?

That being said, I retried the demo app with the latest changes and it is unchanged. Still accumulates 1MB of unreleased memory quickly.

**Comment by kjpou1** [comment]
The Grid property is manually cleaned up because we do not know when it should be cleaned up to be honest.

Right now with the sample you are running only one effect on the node.  What if you want to run two different effects.  Internally with the Grid there is memory allocated and a render target backing that effect and grid.  Each time a Grid is created and torn down there are a lot things going on behind the scenes.  Allocation of memory of the rendertarget, attaching that rendertarget to receive the rendering, actually rendering the node to the rendertarget and then and only then it is ready to execute the actual effect.  If the developer knows before hand that multiple effects are to be run then he runs effect 1 first, effectively creating all the grid backing resources once, the effect runs and the next effect in the sequence runs next using the same backing resources as the first one without having to recreate them again.  When the developer is done with all of his effect sequence then he sets the Grid to null effectively tearing down all the backing resources and hopefully that gets rid of the memory associated.  

To automatically clean up the grid what we would do is set the grid to null internally but we only know that the effect is "stopped" internally, not why it was stopped.  What happens if the user sets all actions paused which also stops the action/effect but leaves the state in tact per users request or uses CCStopGrid in the sequence and then wants to restart it later where it left off.  The outcome then becomes that we have left the effect state basically invalid because we have cleared the the Grid before the developer wanted us to.  Not sure I see a way around that.

**Comment by kjpou1** [comment]
I may be reading this wrong but here is the effect of setting the Grid to null.  This is of course after my commit to dispose of the Grid resources specifically.

https://files.slack.com/files-pri/T03C6CW9H-F04AALN2Z/pasted_image_at_2015_04_07_11_07.png

In Run 1 shows the effect of never setting the Grid to null.  The second run shows little spikes where the effect is run and then the grid is set to null.

**Comment by Krumelur** [comment]
Thanks for the detailed explanations. Learning more about the internals of CocosSharp every day :-)
