### ISSUE TITLE
Calling CCScene.AddEventListener results in crash when obtaining CCTouch locations

### ISSUE THREAD

**Issue by vchelaru** [mono/CocosSharp#190]
I believe this might be the case, but I can't be sure as I didn't get into the code.

I had the following code (reduced for simplicity):

```
var touchListener = new CCEventListenerTouchAllAtOnce ();
touchListener.OnTouchesMoved = HandleTouchesMoved;
ccSceneInstance.AddEventListener (touchListener);
...
void HandleTouchesMoved (System.Collections.Generic.List<CCTouch> touches, CCEvent touchEvent)
{
  var item = touches.FirstOrDefault;
  if(item != null)
  {
    var location = item.Location; // <- This crashed
  }
}

```

I switched to a CCLayer and all seemed to work. 

The exception was difficult to track, especially in Visual Studio which gives no callstack or access to the $exception variable.  

Is it possible to detect whether a compatible object is being used when AddEventListener is called rather than when the event occurs?

**Comment by omarabdellatif** [comment]
Can confirm that this bug exists, as I had the exact same issue. The exception itself is thrown when trying to access the Location property on a CCTouch.

**Comment by rtabbara** [comment]
As mentioned in the wiki [here](https://github.com/mono/CocosSharp/wiki/Key-Differences#sanitized-hierarchy), a scene serves two purposes:

1. Either explicitly or implicitly (when setting the default design-resolution) defines the renderable viewport
2. Is a container for all layers within that scene

While a <code>CCLayer</code>'s role is to:

1. Either explicitly or implicitly (again, done when setting the default design-resolution) define the corresponding <code>CCCamera</code> which specifies the visible world bounds.

2. Container for all other game-nodes (sprites etc.) that are positioned/scaled relative to the layer's world coordinate system.

So hopefully you can see that attempting to get a <code>CCTouch</code>'s location (which is in world-coordinates) from a scene makes no sense because a scene a has no corresponding <code>CCCamera</code> and hence no world-coordinate system. Instead, if you are adding a touch listener to a scene, then you alternatively have access to <code>LocationOnScreen</code> which is independent of any cameras.

But this issue has touched on a more general problem. Historically, <code>CCScene</code> was awkwardly derived from <code>CCNode</code>, giving users carte blanche to add a <code>CCScene</code> instance anywhere along the scene-graph, even though the proper usage is that a sole scene should be present at the root of the graph. 

More importantly, even though a scene should *only* have <code>CCLayer's</code> as its children, as a subclass of <code>CCNode</code>, this can not (at least cleanly) be enforced.

So we need think about whether we should detach <code>CCScene</code> from <code>CCNode</code>, making it a stand-alone class. In this way, we could insist that a scene is the root of all renderable game-content and define methods such as <code>AddLayer</code> to avoid any potential misunderstanding about its role.

But there's obviously trade-offs that we need to take into account (particularly with the existing code-base), so we'll need to consider this very carefully.

**Comment by vchelaru** [comment]
Thanks @rtabbara 

I should have been clear that I didn't necessarily intend that CCScene should be used as an event listener container, but rather just what you said - that the interface should reinforce the intended usage. Otherwise it's a class full of "gotchas".

**Comment by vchelaru** [comment]
More detail - it turns out that adding a listener to a CCSprite will cause a crash *sometimes* but not always. This can be very confusing behavior.
