### ISSUE TITLE
Very slow when loading scene with several tens of sprites

### ISSUE THREAD

**Issue by imkow** [mono/CocosSharp#224]
guys, why its so slow when loading scene with several tens of sprites on CocosSharp?! Cocos2d-XNA is much better with that, and cocos2d-x is very fast too.

This problem makes CocosSharp nearly useless. Solve it. Thanks.

**Comment by rtabbara** [comment]
@imkow Are you using the latest NuGet package or building directly from the repo? What platform?

**Comment by imkow** [comment]
@rtabbara both 1.4 from nugget and the git repo are tested.

**Comment by rtabbara** [comment]
@imkow Our master branch now incorporates a new renderer pipeline as described [here](https://github.com/mono/CocosSharp/issues/228). In particular, we now have automatic batching without the need to use <code>CCSpriteBatchNode</code>. Our tests on a variety of platforms have shown a substantial improvement to performance, particularly when rendering a large number of sprites.

So with all due respect, what you're saying doesn't really make sense at least with our current repo. If you could provide a sample project showcasing the problem you're encountering then we can take a look, otherwise I am at a loss to explain your issue.

**Comment by imkow** [comment]
@rtabbara sorry, forgot to mention it's on Android with Xamarin.Android. Will this new approach be smooth on Android?

**Comment by rtabbara** [comment]
@imkow Yes, the renderer pipeline changes in master should also be applicable to Android. Closing this issue for now as what you're encountering is not replicable.
