### ISSUE TITLE
Font size is way too small on Android

### ISSUE THREAD

**Issue by vchelaru** [mono/CocosSharp#264]
The following code:

			variableLabel = new CCLabel ("Position", "Arial", 46, CCLabelFormat.SystemFont);
			variableLabel.HorizontalAlignment = CCTextAlignment.Left;
			variableLabel.AnchorPoint = new CCPoint (0, 0);
			variableLabel.PositionX = 48;
			variableLabel.PositionY = 390;
			this.AddChild (variableLabel);

results in the following (Nexus 4) (see the "Position" text):

![screenshot1](https://cloud.githubusercontent.com/assets/729631/8639110/eb7289ea-288c-11e5-827d-d54775f32751.PNG)

Running the same code on iOS results in the following (iPhone 4s):

![screen shot 2015-07-12 at 11 59 28 am](https://cloud.githubusercontent.com/assets/729631/8639131/8f3fe54a-288d-11e5-991f-28f284c27317.png)

Changing the font on Android does actually impact the font size, but it's *much* smaller on Android than on iOS. A font size of 10 is still legible on iOS, but it appears 2 pixels tall on Android and cannot be read.

For a cross platform project that shows this in action, see here:

https://github.com/xamarin/mobile-samples/tree/master/CCAction

**Comment by kjpou1** [comment]
@vchelaru Not exactly sure what we can do about the font size differences.  They are pretty much always going to be different across platforms and devices.  All we do is pass the size on to the system and let it do it's thing.

If you have any suggestions we are more than open but truthfully it is outlined quite clearly in the documentation that this could be a problem.

**Comment by vchelaru** [comment]
I do understand that the size might be different, but in this case it's probably a 5:1 difference between iOS and Android. 

To answer your question about what might be done, what exactly does that number mean? Is it the number of pixels tall?  Is it the 'point size' of the font? Is it some arbitrary number which means nothing except a size relative to other sizes on the same hardware?

**Comment by alexsorokoletov** [comment]
@vchelaru Are you checking this on real devices? Is Nexus4 a tablet or a phone? I have a game with SystemFonts and havent seen this problem

**Comment by kjpou1** [comment]
@vchelaru The size parameter basically depends on the native interface.

In this instance for Android it is the [TextPaint](http://developer.android.com/reference/android/text/TextPaint.html) interface.  The [setTextSize](http://developer.android.com/reference/android/graphics/Paint.html#setTextSize(float) ) parameter is what controls the definition.  Which is `Set the paint's text size. This value must be > 0`.  So truthfully here I am not sure what the size actually means.

For iOS and Mac [NSFont](https://developer.apple.com/library/prerelease/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSFont_Class/index.html#//apple_ref/occ/clm/NSFont/fontWithName:size:) is used.  Here the size means `fontSize - The size in points to which the font is scaled`.

For Windows uses [TextFormat](https://msdn.microsoft.com/en-us/library/windows/desktop/dd316628(v=vs.85).aspx).  Where the text size is defined as `font size in DIP unites`.  The FontSize parameter that is passed to CCLabel would most likely be 'em' because I internally convert this to DIP before creating the TextFormat.

Now we come to .ttf files.  This really seems confusing because each platform really takes their liberties here.

**Comment by kjpou1** [comment]
@vchelaru Can not remember if there was any points to be addressed here.  Is there more info that needs to be provided?

**Comment by alexsorokoletov** [comment]
by the way, same binary produces different font sizes on WP8.1 and WM10

**Comment by vchelaru** [comment]
@kjpou1 My apologies for not responding sooner, I have been away for a while.

To answer your question, I do not think that documenting that text sizes will differ on platforms is a sufficient fix for this problem. Text objects, just like sprites or shapes, are visual elements which someone may lay out in an external tool or code on one platform and then expect to work on another. As I see it, the whole point of engines like CocosSharp is to eliminate the need for "#if ANDROID, #elif IOS". It should be coded the exact same way on all platforms and it should appear the same on all platforms.

My suggestion is that we figure out a way to make the fonts the same on all platforms. Maybe that means we have a bool like UseConsistentSizes on the CCLabel, so we aren't breaking old projects. I know stuff like that sucks but I really do think that the inconsistency here is going to create headaches all the way from people coding their layouts all the way up to anyone making tools or converters for existing tools for CocosSharp.

**Comment by rtabbara** [comment]
@vchelaru I have tested system fonts on a real Android device (MotoG) as well as on the Nexus4/5 simulator and am getting consistent font-sizing relative to iOS. So I'm not sure exactly why you encountered this behaviour. I did notice that the sample you referenced uses CocosSharp 1.5, so perhaps modernising the sample to the latest CocosSharp might help solve the issue you're encountering.

With that in mind, I'm going to close this issue for now, but feel free to reopen if you're still observing this problem with the latest code base.
