### ISSUE TITLE
Current CocosSharp template does not compile

### ISSUE THREAD

**Issue by vchelaru** [mono/CocosSharp#332]
I created a new CocosSharp project on OSX. It includes a iOS, Android, and PCL project. None of the three projects have CocosSharp Package. I had to manually include CocosSharp 1.7.0.0-pre to compile. This is extra confusing because people may not check "Show pre-release packages".

**Comment by vchelaru** [comment]
Even when adding CocosSharp, the project does not compile because of a missing reference to CocosSharpView.

**Comment by kjpou1** [comment]
Just created a new CS project added the pre release nuget packages, to all projects, and compiled.  No problem as far as I can tell.  Yes it is confusing because the NuGets are marked as pre-release but was documented in the Release notes that one had to select the show pre-release.  Hopefully we can work this out with the next pre-release.  Visual Studio does not have this problem with the templates.

**Comment by kjpou1** [comment]
Also, if you are using the forms templates then you need to add the CocosSharp.Forms package and not just CocosSharp.

**Comment by rtabbara** [comment]
@vchelaru As @kjpou1 mentioned, you will need the CocosSharp.Forms package to build these templates, so closing this issue for now.
