### ISSUE TITLE
Tiled tile map artifacts when resized 2x,3x etc.

### ISSUE THREAD

**Issue by witlock** [mono/CocosSharp#335]
This is taken from the official Tiled example (https://developer.xamarin.com/guides/cross-platform/game_development/cocossharp/tiled/):

http://i.imgur.com/M39dmUi.png
The one pixel lines are kind of the problem I'm talking about.

I'm not trying to fit a certain size map on my screen. All I'm doing is displaying as much of the map as my camera/screen size allows.

Mine:
![artifacts](https://cloud.githubusercontent.com/assets/8792184/11809008/959a8f8e-a32c-11e5-9df0-8ff4d252c6a0.jpg)

**Comment by rtabbara** [comment]
@witlock This is somewhat related to #338 and #339. Historically, to avoid border artefacts, the actual texture area used for any given tile is slightly reduced. After, #338, one can now toggle this behaviour on and off by using the <code>HalfTexelOffset</code> property. There's also the static <code>CCTileMap.DefaultHalfTexelOffset</code> that you can set as once-off to apply to all your tile-maps.. However, to maintain pre-existing behaviour, by default this is set to true.

I think once you turn off this property, as well as ensure that the tile map's <code>Antialiasing</code> is also off, then you should get the desired behaviour.

But in general, if you want something a bit more robust, I would recommend laying out your tiles in such a way so that there aren't high-contrast 1 pixel borders around a given tile. In other words, if the borders of your tiles are as homogeneous as possible, then this greatly reduces the visual effect of any scaling inconsistencies.

**Comment by witlock** [comment]
I finally achieved the results I desire, but still messing around with CCViewResolutionPolicy and things being crushed when the window is resized
