### ISSUE TITLE
One pixel border around isometric tile map

### ISSUE THREAD

**Issue by Krumelur** [mono/CocosSharp#339]
Testing isometric tile maps on iOS.

My game view is setup like this:

```
gameView.DesignResolution = new CCSizeI (1920, 1080);
gameView.ResolutionPolicy = CCViewResolutionPolicy.ShowAll;
```

My TMX map is 30x33 tiles (sized 64x32), which results in 30x64 = 1.920 pixels width and 33x32 = 1.056 pixels height. ~~This means the entire map should fit on the screen without any scaling.~~

The result however shows that:

* There is a border around each tile
* ~~The width is wider than 1.920 and the map is cropped on the left edge~~

![bildschirmfoto 2015-12-17 um 15 28 22](https://cloud.githubusercontent.com/assets/574373/11872078/bf3af484-a4d3-11e5-9da1-151bd91929ae.png)

Map and textures: https://dl.dropboxusercontent.com/u/111612273/CocosSharp_tiles_border_issue.zip

**Comment by rtabbara** [comment]
@Krumelur your tile-map is not perfectly diagonal. If you'll notice the left-most tile is at (0,32) while the right-most is at (29,0). So your calculation of the width is incorrect.

**Comment by Krumelur** [comment]
You are right about the dimensions.

**Comment by Krumelur** [comment]
I'm getting much better results by turning anti aliasing off `map.Antialiased = false;`

Still, there are incorrect pixels.

iPhone 6:
![iphone6 antialias](https://cloud.githubusercontent.com/assets/574373/11873867/f5a58cd8-a4dc-11e5-873f-67da811ae3dd.png)

iPhone 6+ (= design resolution)
![bildschirmfoto 2015-12-17 um 16 40 52](https://cloud.githubusercontent.com/assets/574373/11873866/f3cd9bbc-a4dc-11e5-8e02-303bf5f281ff.png)

**Comment by rtabbara** [comment]
@Krumelur I have inspected the pre-existing tile-map isometric tests and from what I've seen, the trick is to make the tile-map dimensions of the map itself slightly smaller and/or offset than the tile dimensions of the tile-set as seen below

![isometric_offset](https://cloud.githubusercontent.com/assets/3273442/11911110/1702d308-a65f-11e5-976d-8d82aafee2e3.png)

In this way, there's a slight overrun of each tile quad which helps to remove these border artefacts. I'm by no means on expert with TMX, but given this problem is not unique to CocosSharp, I'm going to close this issue for now.
